<?php


namespace QuinenCake\Controller;


use Cake\Event\Event;

class IndexController extends AppController
{
    use InitTrait;
    public function beforeRender(Event $event)
    {
        $this->initBs4Helpers();
        $this->initUiHelpers();

        $this->viewBuilder()->setLayout('QuinenCake.bs4_cdn');

        return parent::beforeRender($event); // TODO: Change the autogenerated stub

    }

    public function bdd()
    {
        $bdds = [];
        $this->set(compact('bdds'));
    }
}
